name: agc_tp
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - numpy=1.19.5
  - nwalign3
  - vsearch
  - pip
  - pip:
      - pytest
      - pytest-cov
      - pylint

